# Multi dimentional array with numpy

In [200]:
# %pip install matplotlib

import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])

print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]


In [14]:
a2 = np.array([[[[1,2,3],[4,5,6]]
              ,[[7,8,9],[10,11,12]]],
               [[[13,14,15],[16,17,18]],
              [[13,14,15],[16,17,18]]], [[[13,14,15],[16,17,18]],
              [[13,14,15],[16,17,18]]]])
print(a2.ndim)
print(a2[1,1,1,1])

4
17


# Shape

In [15]:
a2.shape
a2.size

36

In [ ]:


l = list(range(10))
l2=[]
for i in range(len(l) -1, -1 ,-1):
  l2.append(l[i])  

print(l2)



l = list(range(10))
l
l2= []

for i in range(len(l) -1, -1, -1):
  l2.append(l[i])

print(l2)



[0.64604302 0.4615649  0.35844868 0.84792526 0.94253136 0.00114712
 0.51934734 0.73662625 0.69194852 0.51187574 0.01085517 0.7566395
 0.09913543 0.31883459 0.73913919 0.20185827 0.22979627 0.52953788
 0.83264763 0.18523523 0.51223831 0.19975224 0.93094825 0.63442974
 0.06434492 0.00122561 0.7101625  0.91998282 0.89725247 0.67431502
 0.96933757 0.10216633 0.68758376 0.45570067 0.25634982 0.2839496
 0.22837287 0.5572541  0.44605781 0.57479684 0.96334711 0.00520721
 0.18813679 0.1032955  0.95022669 0.2518673  0.75433627 0.34463432
 0.61646424 0.47657258 0.30071944 0.49429498 0.11499084 0.32810091
 0.65541672 0.96104448 0.99797879 0.53311949 0.95740053 0.5223853
 0.2421664  0.60076045 0.91126794 0.75856728 0.7328202  0.95126936
 0.97615796 0.21657011 0.07484134 0.35987214 0.73467488 0.85847478
 0.34249804 0.43603462 0.73272633 0.09504535 0.66008903 0.76065195
 0.49198052 0.97784954 0.66846735 0.24038699 0.31659444 0.40461255
 0.39932081 0.51113982 0.50247605 0.73372115 0.69063113 0.2685099

In [ ]:
ar = np.random.rand(1000)
plt.hist(ar,bins=10)


In [7]:
b = np.random.randn(1000)
# plt.hist(b,bins=10)

In [41]:
c = np.random.rand(2,3,4,2)


In [106]:
d = np.arange(100)

s=d[0:35]
s[20]=250

index_of = np.where(d == 250)
print(f"The index of element is: {index_of[0][0]}")
d
d[index_of]= 20
d


The index of element is: 20


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [257]:
D = np.arange(36).reshape(2,6,3)
np.random.shuffle(D)
D.sort(axis=2)
D
D[D<8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [258]:
al = la.inv(np.random.rand(3,3))
al.sort(axis=1)
al

array([[-7.27417849, -0.44580981,  5.95936963],
       [-2.43583255,  0.86915193,  1.70345227],
       [-1.80597521, -0.27620983,  3.98915221]])

In [ ]:
A = np.arange(1,100)
A[[3,5,6]]
B = A[(A < 20) & (A > 10)]
B = A[(A < 11) | (A > 20)]
B

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])