# Review from classes

In [2]:
# %pip install pandas

import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la
import pandas as pd

In [3]:
a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3,4))
c = np.random.randint(10, size=(3,4,10))
print(a," a")
try:
    ind = np.where(a == 8)
    print("The index of elements is ", ind[0][0])
except Exception as e:
    print("Index error:", e)


[6 2 2 6 7 9]  a
Index error: index 0 is out of bounds for axis 0 with size 0


In [4]:
D = np.arange(60).reshape(4,3,5)
B=D.flatten()
R=B.reshape((30,2))
T=R.transpose()
T


array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59]])

In [5]:
Y = np.random.randint(10, size=(3,5))
D = np.random.randint(10, size=(3,5))

try:
  F = np.concatenate([Y,D])
  print(F)
except Exception as e:
    print(" error:", e)





[[5 3 9 2 0]
 [6 5 3 5 7]
 [3 3 3 9 8]
 [8 0 3 4 3]
 [5 8 6 4 0]
 [0 8 7 7 5]]


In [11]:

values = np.random.randint(1, 4, size=(2,2,2))
print("values:\n", values)
print("\n==========")
# b = np.array([
#     [[2, 2],
#      [4,10]]
#     ])
# print("b:\n", b)
# print("\n==========")
# print("Result:\n", values * b)
print() 
print('sum ',values.sum(axis=0))
print() 

# values.cumprod()
# data = pd.read_csv('../../president_heights.csv')

# height = np.array(data['height(cm)'])
# name = np.array(data['name'])
# tallest_index = height.argmax()
# shortest_index = height.argmin()

# print('Average height:  ', height.mean(),) 
# print('Standart daviation:    ', height.std()) 
# print('Minimum height:  ', height.min(), name[shortest_index]) 
# print('Maximum height:  ', height.max(), name[tallest_index]) 



values:
 [[[2 1]
  [1 1]]

 [[2 3]
  [2 1]]]


sum  [[4 4]
 [3 2]]



In [12]:
a = np.array([1, 2, 3, 4, 5])   # shape (5,)
b = np.array([10])      # shape (3,)
print(a * b)

[10 20 30 40 50]
