In [2]:
# %pip install seaborn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


In [65]:
v1 = np.array([2,7,1])
v2 = np.array([[2,1,2], [2,1,2]])

s = np.dot(v2, v1)
s


array([13, 13])

In [43]:
# 🧠 Each user represented by [age, monthly_purchases, time_spent_on_app(mins)]
users = np.array([
    [25, 3, 40],
    [27, 5, 42],
    [35, 10, 15],
    [23, 4, 41],
    [60, 1, 10],
    [26, 3, 38],
])

user_names = np.array(["Alice", "Bob", "Charlie", "Diana", "Edward", "Frank"])

# 🧍 New user vector
new_user = np.array([26, 4, 39])

# 🧮 Compute distance using np.linalg.norm for each user
distances = np.array([np.linalg.norm(u - new_user) for u in users])

# Combine into DataFrame
df = pd.DataFrame({
    'User': user_names,
    'Distance': distances
}).sort_values(by='Distance')

# 🎯 Show nearest 3 neighbors
print(df.round().head(3))

    User  Distance
5  Frank       1.0
0  Alice       2.0
1    Bob       3.0


In [51]:

# Define a vector
v = np.array([250, 40, 5,5,8,900,8,300,7])
print(f"Original vector: {v}")

# Compute the L2 norm (vector length)
v_norm = np.linalg.norm(v)
print(f"L2 Norm: {v_norm}")

# Normalize the vector (create a unit vector)
v_unit = v / v_norm
print(f"Unit vector: {v_unit}")

# Round and print values for readability
for i in v_unit:
    print(round(i))

Original vector: [250  40   5   5   8 900   8 300   7]
L2 Norm: 982.0015274937203
Unit vector: [0.25458209 0.04073313 0.00509164 0.00509164 0.00814663 0.91649552
 0.00814663 0.30549851 0.0071283 ]
0
0
0
0
0
1
0
0
0


In [25]:
v = np.array ([3, 4, 5])


L1_norm_np = np.linalg.norm(v, ord=1)
print(L1_norm_np)

L2_norm_np = np.linalg.norm(v, ord=2)
print(L2_norm_np)

max_norm_np = np.linalg.norm(v, ord=np.inf)
print(max_norm_np)


12.0
7.0710678118654755
5.0


In [ ]:

users = np.array([
    [25, 3, 40],
    [27, 5, 42],
    [35, 10, 15],
    [23, 4, 41],
    [60, 1, 10],
    [26, 3, 38],
])

user_names = np.array(["Alice", "Bob", "Charlie", "Diana", "Edward", "Frank"])

# 🧍 New user vector
new_user = np.array([26, 4, 39])


distances_raw = np.array([np.linalg.norm(u - new_user) for u in users])

df_raw = pd.DataFrame({
    'User': user_names,
    'Distance (Raw)': distances_raw
}).sort_values(by='Distance (Raw)')


users_min = users.min(axis=0)
users_max = users.max(axis=0)

users_norm = (users - users_min) / (users_max - users_min)
new_user_norm = (new_user - users_min) / (users_max - users_min)

# Compute distances again
distances_norm = np.array([np.linalg.norm(u - new_user_norm) for u in users_norm])

df_norm = pd.DataFrame({
    'User': user_names,
    'Distance (Normalized)': distances_norm
}).sort_values(by='Distance (Normalized)')


df_compare = pd.concat([df_raw.set_index('User'), df_norm.set_index('User')], axis=1)
print(df_compare.sort_values(by='Distance (Normalized)'))

         Distance (Raw)  Distance (Normalized)
User                                          
Diana          3.605551               0.102374
Frank          1.414214               0.115422
Alice          1.732051               0.118544
Bob            3.316625               0.147869
Charlie       26.324893               1.032527
Edward        44.788391               1.332971


In [ ]:
v1 = np.array([2,7,1])
v2 = np.array([[2,1,2], [2,1,2]])

s = np.dot(v2, v1.T)
# print(s)


A = np.array([[1, 2, 3],
              [4, 5, 6]])   

B = np.array([[7, 8, 9],
              [10, 11, 12]]) 


C = np.dot(A.T, B) # Transpose
print(C)


[[47 52 57]
 [64 71 78]
 [81 90 99]]


50

In [88]:
import numpy as np

X_bad = np.array([[1,2,3],
                  [2,4,6],
                  [3,6,9]])
X_good = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,10]])

print(np.linalg.matrix_rank(X_bad))  # 1  (bad)
print(np.linalg.matrix_rank(X_good)) # 3  (good)

1
3


In [93]:
import numpy as np

X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [2, 7, 4]
])


print(np.linalg.matrix_rank(X))


3


In [95]:
# Cros multiplacation 
A = np.array([[2, 3],
              [4, 6]])

det = np.linalg.det(A)
print(det)

0.0


In [98]:
# Identifier is a stablizer. 

A = np.array([[2, 4],
              [4, 8]])  # determinant = 0 (singular)

I = np.eye(2)
A_fixed = A + 0.1 * I   # stabilize it

print(np.linalg.det(A))       # 0.0 ❌
print(np.linalg.det(A_fixed)) # 0.4 ✅
print(A_fixed)

0.0
1.01
[[2.1 4. ]
 [4.  8.1]]


In [101]:
X = np.array([[1, 1],
              [1, 2],
              [1, 3]])
y = np.array([2, 2.5, 3.5])

w = np.linalg.inv(X.T @ X) @ (X.T @ y)
print(w)

[1.16666667 0.75      ]


In [106]:

# Symbol
# Meaning
# A
# your square matrix
# v
# Eigenvector (a direction that stays the same)
# \lambda
# Eigenvalue (how much it’s stretched or compressed)


A = np.array([[5, 0],
              [0, 5]])

values, vectors = np.linalg.eig(A)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [5. 5.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]
